// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/protobuf/unittest_import_public.proto

#ifndef PROTOBUF_google_2fprotobuf_2funittest_5fimport_5fpublic_2eproto__INCLUDED
#define PROTOBUF_google_2fprotobuf_2funittest_5fimport_5fpublic_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3001000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3001000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace protobuf_unittest_import {

// Internal implementation detail -- do not call these.
void protobuf_AddDesc_google_2fprotobuf_2funittest_5fimport_5fpublic_2eproto();
void protobuf_InitDefaults_google_2fprotobuf_2funittest_5fimport_5fpublic_2eproto();
void protobuf_AssignDesc_google_2fprotobuf_2funittest_5fimport_5fpublic_2eproto();
void protobuf_ShutdownFile_google_2fprotobuf_2funittest_5fimport_5fpublic_2eproto();

class PublicImportMessage;

// ===================================================================

class PublicImportMessage : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:protobuf_unittest_import.PublicImportMessage) */ {
 public:
  PublicImportMessage();
  virtual ~PublicImportMessage();

  PublicImportMessage(const PublicImportMessage& from);

  inline PublicImportMessage& operator=(const PublicImportMessage& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const PublicImportMessage& default_instance();

  static const PublicImportMessage* internal_default_instance();

  void Swap(PublicImportMessage* other);

  // implements Message ----------------------------------------------

  inline PublicImportMessage* New() const { return New(NULL); }

  PublicImportMessage* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const PublicImportMessage& from);
  void MergeFrom(const PublicImportMessage& from);
  void Clear();
  bool IsInitialized() const;

  size_t ByteSizeLong() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(PublicImportMessage* other);
  void UnsafeMergeFrom(const PublicImportMessage& from);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional int32 e = 1;
  bool has_e() const;
  void clear_e();
  static const int kEFieldNumber = 1;
  ::google::protobuf::int32 e() const;
  void set_e(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:protobuf_unittest_import.PublicImportMessage)
 private:
  inline void set_has_e();
  inline void clear_has_e();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable int _cached_size_;
  ::google::protobuf::int32 e_;
  friend void  protobuf_InitDefaults_google_2fprotobuf_2funittest_5fimport_5fpublic_2eproto_impl();
  friend void  protobuf_AddDesc_google_2fprotobuf_2funittest_5fimport_5fpublic_2eproto_impl();
  friend void protobuf_AssignDesc_google_2fprotobuf_2funittest_5fimport_5fpublic_2eproto();
  friend void protobuf_ShutdownFile_google_2fprotobuf_2funittest_5fimport_5fpublic_2eproto();

  void InitAsDefaultInstance();
};
extern ::google::protobuf::internal::ExplicitlyConstructed<PublicImportMessage> PublicImportMessage_default_instance_;

// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// PublicImportMessage

// optional int32 e = 1;
inline bool PublicImportMessage::has_e() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void PublicImportMessage::set_has_e() {
  _has_bits_[0] |= 0x00000001u;
}
inline void PublicImportMessage::clear_has_e() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void PublicImportMessage::clear_e() {
  e_ = 0;
  clear_has_e();
}
inline ::google::protobuf::int32 PublicImportMessage::e() const {
  // @@protoc_insertion_point(field_get:protobuf_unittest_import.PublicImportMessage.e)
  return e_;
}
inline void PublicImportMessage::set_e(::google::protobuf::int32 value) {
  set_has_e();
  e_ = value;
  // @@protoc_insertion_point(field_set:protobuf_unittest_import.PublicImportMessage.e)
}

inline const PublicImportMessage* PublicImportMessage::internal_default_instance() {
  return &PublicImportMessage_default_instance_.get();
}
#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

}  // namespace protobuf_unittest_import

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_google_2fprotobuf_2funittest_5fimport_5fpublic_2eproto__INCLUDED
